// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4zE4bpesE1k3mz2EFrK7-mlAdHOURxyg',
    appId: '1:618058460930:web:e19be5c9e9aac89fb51c1b',
    messagingSenderId: '618058460930',
    projectId: 'hackhaton-ef4fa',
    authDomain: 'hackhaton-ef4fa.firebaseapp.com',
    databaseURL: 'https://hackhaton-ef4fa-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'hackhaton-ef4fa.appspot.com',
    measurementId: 'G-4EPTCSWDP6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBe70eLvfH4pA3nSFaaudAk4dAgqyj7w2A',
    appId: '1:618058460930:android:dd08738633d71a45b51c1b',
    messagingSenderId: '618058460930',
    projectId: 'hackhaton-ef4fa',
    databaseURL: 'https://hackhaton-ef4fa-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'hackhaton-ef4fa.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhZqFVnS2gF_hdM-cBQ3c47LoC6bDGgLU',
    appId: '1:618058460930:ios:09455234a7654610b51c1b',
    messagingSenderId: '618058460930',
    projectId: 'hackhaton-ef4fa',
    databaseURL: 'https://hackhaton-ef4fa-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'hackhaton-ef4fa.appspot.com',
    iosBundleId: 'com.example.mpit',
  );
}
